// <auto-generated />
using System;
using GamzeArici.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamzeArici.Migrations
{
    [DbContext(typeof(GamzeAriciContext))]
    [Migration("20220626175736_vtyukle")]
    partial class vtyukle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamzeArici.Entities.Islemler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int>("OkuyucuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("OkuyucuId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("GamzeArici.Entities.Kitaplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RafId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RafId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("GamzeArici.Entities.Okuyucular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Okuyucular");
                });

            modelBuilder.Entity("GamzeArici.Entities.Raflar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RafAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Raflar");
                });

            modelBuilder.Entity("GamzeArici.Entities.Islemler", b =>
                {
                    b.HasOne("GamzeArici.Entities.Kitaplar", "Kitap")
                        .WithMany("Islemler")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamzeArici.Entities.Okuyucular", "Okuyucu")
                        .WithMany("Islemler")
                        .HasForeignKey("OkuyucuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Okuyucu");
                });

            modelBuilder.Entity("GamzeArici.Entities.Kitaplar", b =>
                {
                    b.HasOne("GamzeArici.Entities.Raflar", "raf")
                        .WithMany("Kitaplar")
                        .HasForeignKey("RafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("raf");
                });

            modelBuilder.Entity("GamzeArici.Entities.Kitaplar", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("GamzeArici.Entities.Okuyucular", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("GamzeArici.Entities.Raflar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
